@echo off
start /d "D:\work\eclipse" eclipse.exe "E:\work\workspace\xpmPlusGdgj\src\main\resources\conf\i18n\英文V1.0_2016030901.txt"
start /d "D:\work\eclipse" eclipse.exe "E:\work\workspace\xpmPlusGdgj\src\main\resources\conf\i18n\中文V1.0_2016030901.txt"
start /d "D:\work\eclipse" eclipse.exe "E:\work\workspace\xpmPlusGdgj\src\main\resources\conf\i18n\messages_en.properties"
start /d "D:\work\eclipse" eclipse.exe "E:\work\workspace\xpmPlusGdgj\src\main\resources\conf\i18n\messages_zh.properties"
start /d "D:\work\eclipse" eclipse.exe "E:\work\workspace\xpmPlusGdgj\webContent\js\i18n\messages_zh.properties"
start /d "D:\work\eclipse" eclipse.exe "E:\work\workspace\xpmPlusGdgj\webContent\js\i18n\messages.properties"
start /d "D:\work\eclipse" eclipse.exe "E:\work\workspace\xpmPlusGdgj\webContent\css\base.css"
start /d "D:\work\eclipse" eclipse.exe "E:\work\workspace\xpmPlusGdgj\webContent\pages\demo\iconGraphics\aliIcon.jsp"
start /d "D:\work\eclipse" eclipse.exe "E:\work\workspace\xpmPlusGdgj\webContent\pages\demo\projectButton\projectButton.jsp"
start "" "E:\work\workspace\xpmPlusGdgj\webContent\css\iconfont"